### ISSUE TITLE
docker image 

### ISSUE THREAD

**Issue by kostyrev** [acme-dns/acme-dns#141]
What registry do you use to publish you code?  
I found [this](https://hub.docker.com/r/joohoi/acme-dns/builds) but latest build was 2 months ago.  
Could you please update it with [health check](https://github.com/joohoi/acme-dns/commit/aff13a02fb68267895ca8beeaea6331a85e0b686) commit?  
What's your take on building master as latest [automagically](https://docs.docker.com/docker-hub/builds/)?

**Comment by joohoi** [comment]
Hi! That DockerHub link you found is the correct one. I've been basically doing builds upon every release, so even though the `latest` tag follows `master` branch, it has been updated only upon releases this far.

I can't enable automated builds because GitHub deprecated their GitHub Services API, and the only way to enable DockerHub to do the automated builds I would have to give DockerHub full write access to the repository - a thing I don't want to do.

That said, I just triggered a build for for `latest` tag, and the new version now has the health check endpoint.

I feel like this issue is solved, so I'm closing it. If by any means you feel that this is not the case, feel free to comment, and I'll reopen!
