### ISSUE TITLE
Use DNS validation for tls = "letsencrypt"

### ISSUE THREAD

**Issue by danb35** [acme-dns/acme-dns#171]
In light of the recent update to README that seems to pretty strongly encourage using `tls = "letsencrypt'` rather than `tls = "cert"` in the config file, IIRC, acme-dns uses HTTP validation for the former case.  It would be nice if it would instead use DNS validation--many installations may not want to open web ports for this installation to the Internet.  It seems this should be pretty straightforward to do (easy for me to say, of course), since it directly controls that validation mechanism.

~~The only user-facing issue I see with this is setting up the initial DNS CNAME record for _acme-challenge.auth.domain.tld--what subdomain should it point to?~~  As I think about it, this doesn't need to be an issue at all--since acme-dns acts as the authoritative DNS server for its subdomain, it can respond directly to TXT queries on _acme-challenge.auth.domain.tld; no CNAME record needs to be set.

**Comment by HEP85** [comment]
+1 on this
I thought the purpose of this tool is to avoid using the http-01 challenge. I don't want to open another port. As @danb35 suggests, it is completely feasible to use dns-01 challenge, because we have already zone delegation. What is the reasoning behind this?

**Comment by danb35** [comment]
> Add a new entry of "_acme-challenge.auth.domain.tld CNAME [uuid].auth.domain.tld", and now you have CNAME for your auth server in a perfectly fitting way. :)

Sure, that's the easy part.  But you're still obtaining and renewing the certs outside of acme-dns, which the docs now explicitly discourage--they strongly encourage setting `tls = "letsencrypt"`, which would have acme-dns obtain and configure its own cert automatically.  But it only does that using HTTP validation.

**Comment by cfazzini** [comment]
Certainly, if it could update it's own certificate via DNS validation that would be preferred. Another option mostly within the current framework, is to put the TXT record in the config file. This mostly worked, though I had to modify the ParseRecord function because it converts the record to lowercase, which invalidates the authentication string. This also requires a second restart of service (once for TXT record, another for new cert) This approach should prevent the chicken/egg situation of cert expiring, unless the service won't start with an expired certificate. Still requires an external client however.

**Comment by joohoi** [comment]
This was implemented in #190 and is included in v0.8 just released!
