### ISSUE TITLE
How to add other types of records through the API?

### ISSUE THREAD

**Issue by themihai** [acme-dns/acme-dns#27]
The documentations shows how to add TXT records(assuming that you defer the verification from your main DNS server using a CNAME) but I wonder if it supports other record types and if it can be used as the main DNS server(i.e. point the NS records to it). Using a different server just for ACME verifications doesn't seem right.

**Comment by joohoi** [comment]
The static configuration file allows you to add any and all kinds of records you wish, example from the default configuration file:
```
# predefined records served in addition to the TXT
records = [
    # default A
    "auth.example.org. A 192.168.1.100",
    # A 
    "ns1.auth.example.org. A 192.168.1.100",
    "ns2.auth.example.org. A 192.168.1.100",
    # NS
    "auth.example.org. NS ns1.auth.example.org.",
    "auth.example.org. NS ns2.auth.example.org.",
]
```

Using acme-dns as a primary nameserver is discouraged however. It lacks a lot of important functionality that actual name servers carry, for example the zone transfers for master->slave propagation, DNSSEC etc. It was specifically developed to act as a supplementary mean to handle ACME DNS validation in a way that has minimal attack surface and is intentionally limited because of that.
