### ISSUE TITLE
letsencrypt HTTP-01 challenge possible?

### ISSUE THREAD

**Issue by leonkyneur** [acme-dns/acme-dns#35]
Just noticed my certificate cannot renew, I think it's only since LetsEncrypt dropped support for TLS-SNI.

`01/02/2018 12:14:43 pmINFO[0029] http: TLS handshake error from 10.42.176.26:51538: acme/autocert: unable to authorize "xxxxxxx.net"; tried ["tls-sni-02" "tls-sni-01"]`

is there any way I can continue to use autocert for the API but with HTTP-01 challenge?

**Comment by joohoi** [comment]
There is! I'm going to write a quick PR to address that. We need to make the autocert use HTTP-01 challenge instead. Sorry I didn't get around this earlier. 

However, please note that this means that ACME-DNS needs to be able to bind to port 80 as well.

**Comment by joohoi** [comment]
Thanks for opening the issue!

This is now fixed in `master` branch, tag `v0.3`. Please note that you will need to add the new variable to your `config.cfg` as shown [here](https://github.com/joohoi/acme-dns/blob/master/config.cfg#L39-L40).

I changed the Docker image builds to an automated process in Docker hub, so it will take a while for the images to get updated.

Sorry for the inconvenience this has caused, and about not getting around it earlier!

**Comment by leonkyneur** [comment]
Thanks for fixing that and also thanks for for acme-dns 😀
