### ISSUE TITLE
Bad Subdomain

### ISSUE THREAD

**Issue by lukepolo** [acme-dns/acme-dns#52]
Im getting a bad subdomain currently , Ill take down this instance once i get it resolved but : 

```
## Acme-DNS Register
curl -X "POST" "http://159.65.179.47/register"
```

```
## Acme-DNS Update
curl -X "POST" "http://159.65.179.47/update" \
     -H 'Content-Type: application/json; charset=utf-8' \
     -H 'X-Api-Key: n8o2nd7E4JtqWlTEbyEZAjs5mZr1wc8Ehju2SNhG' \
     -H 'X-Api-User: 105f0386-6d4b-41ca-9c17-d5a0481e7e36' \
     -d $'{
  "txt": "test",
  "subdomain": "cc3ddadd-0c05-4e5e-8d3f-2d2b72e9c083"
}'
```
Response : 

```{ error : 'bad_subdomain'}```

Is there something im doing wrong?

**Comment by cpu** [comment]
@lukepolo What commit of `acme-dns` are you running? I think you hit the same thing I did that I fixed in https://github.com/joohoi/acme-dns/pull/42

Sending a `"txt"` with the value `"test"` will be rejected because it isn't exactly 43 characters long like an ACME DNS-01 challenge response. Prior to d542ee03b5292c36f13fe2dddd98c03793ab39b7 `acme-dns` returned a "bad_subdomain" error when the "txt" was invalid.

**Comment by cpu** [comment]
You can test if my theory is correct by sending `"txt":"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"` instead.

**Comment by lukepolo** [comment]
Yup it worked ! Thanks for that.

**Comment by cpu** [comment]
@lukepolo Happy to help!
